name: update-izdavanje

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5'

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib

      - name: Run izdavanje scraper
        run: jupyter nbconvert --to notebook --execute "prodaja.ipynb" --output "prodaja-output.ipynb"

      - name: Commit and push results
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
